---

name: "Generate RDS engine versions table"

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0/2 0 * * *"  # every midnight

# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  update_rds_versions:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # working-directory: .github/workflows
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      # OIDC Identity Provider
      # https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/identity_providers/details/OPENID/arn%3Aaws%3Aiam%3A%3A012096835438%3Aoidc-provider%2Ftoken.actions.githubusercontent.com

      # https://github.com/unfunco/terraform-aws-oidc-github#references
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/RDSDBVersionDescriber
          role-to-assume: arn:aws:iam::938988851154:role/RDSDBVersionDescriber
          # role-session-name: RDSDescribeDBEngineVersions
          aws-region: us-east-1

      - name: Test STS caller identity
        run: aws sts get-caller-identity

      # Authenticate with tec-cpe-shs-prd

      - name: Update RDS Versions Table
        run: |
          aws rds describe-db-engine-versions --output json --query 'DBEngineVersions[*].{Engine:Engine,EngineVersion:EngineVersion}' > rds-db-versions.json;
          cat ./rds-db-versions.json;
          ./gen_engine_version_table.py rds-db-versions.json |
            tee preferred_engine_versions.json

      - name: Record change
        id: detect_change
        run: |
          set -xv
          if git diff --stat --exit-code preferred_engine_versions.json; then
            echo "No change detected";
            exit 0;
          fi;
          # Emit change msg: e.g. postgres 15.2 -> 15.3
          { echo -n 'msg="';
            git diff -U0 preferred_engine_versions.json |
              grep '^[+-] ' |
              awk -v RS="^$" -F'"' '{ print $2" "$4" -> "$8 }'  |
              tr -d '\n'
            echo -n '"';
          } | tee -a "$GITHUB_OUTPUT"

      - name: Create Pull Request
        # if: steps.detect_change.output.msg != ""
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          commit-message: "RDS Engine Version Change: ${{ steps.record_change.outputs.msg }}"
          committer: GitHub <noreply@github.com>
          author: "${{ github.actor }}<terraform-aws-TakedaRDS+github-workflow[bot]@users.noreply.github.com>"
          signoff: false
          branch: rds-engine-version-tracker
          delete-branch: false
          title: |
            RDS Engine Version Update: ${{ steps.record_change.outputs.msg }}
          body: |
            RDS Engine Version Update: ${{ steps.record_change.outputs.msg }}

            Version Change Report

              - version change:    ${{ steps.record_change.output.msg }}
              - file:              preferred_engine_versions.json
              - auto-generated by: [shalomb/terraform-aws-TakedaRDS][1]

            [1]: https://github.com/shalomb/terraform-aws-TakedaRDS
          labels: |
            rds-versions-update
            service-standard-change
          assignees: shalomb # "@shalomb/terraform"
          # team-reviewers: |
          #   @shalomb/dbcoeteam
          # reviewers: shalomb
          # milestone: 1
          draft: false

# https://github.com/marketplace/actions/rule-based-pr-manager
# https://github.com/marketplace/actions/rule-based-pr-manager
# https://github.com/marketplace/actions/notify-microsoft-teams
